from Scooter import Scooter
from Bicycle import Bicycle
from ElectricBike import ElectricBike

scut = Scooter()
bici = Bicycle()

''' Pruebas bike hasta neesitar mtto     
bici = Bicycle()
print('1.- Crear objeto bicicleta:')
bici.indicators()
print('2.- Se intenta desbloquear:')
bici.unlock()
bici.indicators()
print('3.- Se acelera el vehiculo')
bici.set_speed(20)
bici.indicators()
print('4.- Se trata de bloquear vehiculo en transito')
bici.lock()
bici.indicators()
print('5.- Se detiene e vehiculo')
bici.set_speed(0)
bici.indicators()
print('6.- Se trata de bloquear vehiculo')
bici.lock()
bici.indicators()
print('7.- Usuario 2 intenta desbloquear:')
bici.unlock()
bici.indicators()
print('8.- Se acelera el vehiculo a 30km/h')
bici.set_speed(30)
bici.indicators()
print('9.- Usuario 2 se detiene')
bici.set_speed(0)
bici.indicators()
print('10.- Usuario 2 termina de usar servicio')
bici.lock()
bici.indicators()
print('11.- Usuario 3 intenta desbloquear:')
bici.unlock()
bici.indicators()
print('12.- Se acelera el vehiculo a 60km/h')
bici.set_speed(60)
bici.indicators()
print('13.- Usuario 3 se detiene')
bici.set_speed(0)
bici.indicators()
print('14.- Usuario 3 termina de usar servicio')
bici.lock()
bici.indicators()
print('15.- Usuario 4 intenta usar el servicio')
bici.unlock()
bici.indicators()
'''

'''
# Pruebas bike desde in-transit hasta deploy
bici = Bicycle()
bici.set_maintenance(True)
bici.indicators()
print('1.- Se pasa el scan')
bici.scan()
bici.indicators()
print('2.- Se pasa el scan')
bici.scan()
bici.indicators()
print('3.- Se hace mantenimiento')
bici.repair()
bici.indicators()
print('4.- Se pasa el scan')
bici.scan()
bici.indicators()
print('5.- Se pasa el scan')
bici.scan()
bici.indicators()
print('6.- Se intenta desbloquear')
bici.unlock()
bici.indicators()
print('7.- Se acelera')
bici.set_speed(10)
bici.indicators()
print('8.- Se detiene')
bici.set_speed(0)
bici.indicators()
print('9.- Se bloquea nuevamente')
bici.lock()
bici.indicators()
'''
